### ISSUE TITLE
NWP flip

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_data_visualization#38]
Currently NWP data is upside down

Need to flip on y axis

<img width="1060" alt="Screenshot 2022-05-16 at 20 32 29" src="https://user-images.githubusercontent.com/34686298/168668390-5e188471-fe03-4db8-9578-445912c3e829.png">

**Comment by peterdudfield** [comment]
Might need to do this with Satellite too, but left to right

**Comment by JackKelly** [comment]
Here's how we flip the x axis in nowcasting_dataset: https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/satellite/satellite_data_source.py#L454

Yeah, in general, I think we should "standardise" on having image arrays start at top-left. i.e. they should plot "the right way up" when plotted without coords.

**Comment by peterdudfield** [comment]
> Here's how we flip the x axis in nowcasting_dataset: https://github.com/openclimatefix/nowcasting_dataset/blob/main/nowcasting_dataset/data_sources/satellite/satellite_data_source.py#L454
> 
> Yeah, in general, I think we should "standardise" on having image arrays start at top-left. i.e. they should plot "the right way up" when plotted without coords.

thanks Jack for this

**Comment by peterdudfield** [comment]
Both done with https://github.com/openclimatefix/nowcasting_data_visualization/pull/40
